/**
 * Type-safe wrapper around the libriichi-wasm bindings.
 *
 * The autogenerated `pkg/libriichi_wasm.d.ts` is a thin descriptor of the
 * raw exports; this module adds:
 *   - parsed return types instead of JSON strings
 *   - lifecycle ergonomics (PlayerStateHandle is explicitly disposable)
 *   - module location lookup that works from anywhere in the tree
 *
 * Build the wasm first:
 *     bash scripts/build-wasm.sh
 *
 * Importing this from .ts files requires Node ≥ 20 and `tsx` (or the
 * compiled .js equivalent under `dist/`).
 */

import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { dirname, resolve as resolvePath } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const pkgPath = resolvePath(__dirname, '../../libriichi-wasm/pkg')

// Use createRequire so we can require() a CommonJS module from this ESM file.
const requireFromHere = createRequire(import.meta.url)
const wasm = requireFromHere(pkgPath) as WasmExports

// ----- Native wasm types (mirror of pkg/libriichi_wasm.d.ts) -----

interface WasmPlayerStateHandle {
  free(): void
  apply_event(mjai_json: string): string
  brief_info(): string
  encode_obs(version: number, at_kan_select: boolean): Float32Array
  encode_obs_mask(version: number, at_kan_select: boolean): Uint8Array
}

interface WasmPlayerStateHandleCtor {
  new (player_id: number): WasmPlayerStateHandle
}

interface WasmExports {
  PlayerStateHandle: WasmPlayerStateHandleCtor
  action_space(): number
  obs_shape(version: number): Uint32Array
  shanten(tile_ids: Uint32Array): number
  tile_id_to_string(id: number): string
  tile_string_to_id(s: string): number
  mjai_event_from_json(json: string): unknown
}

// ----- Typed re-exports -----

export const ACTION_SPACE: number = wasm.action_space()

/** Returns `[channels, 34]` for the given obs version. */
export function obsShape(version: 1 | 2 | 3 | 4): readonly [number, number] {
  const [c, t] = wasm.obs_shape(version)
  return [c, t] as const
}

/** Library version constants for our specific build. */
export const OBS_SHAPE_4 = obsShape(4) // (1012, 34) — our v4 model
export const OBS_SHAPE_3 = obsShape(3) // (934, 34)  — libriichi3p native

/** MJAI tile string ("1m".."9m", "1p".."9p", "1s".."9s",
 *  "E","S","W","N","P","F","C", red dora "5mr","5pr","5sr"). */
export type MjaiTile = string

export function tileIdToString(id: number): MjaiTile {
  return wasm.tile_id_to_string(id)
}

export function tileStringToId(s: MjaiTile): number {
  return wasm.tile_string_to_id(s)
}

export function shanten(tileIds: readonly number[]): number {
  return wasm.shanten(Uint32Array.from(tileIds))
}

/** Result of `apply_event`. Matches libriichi's ActionCandidate. */
export interface ActionCandidate {
  can_discard: boolean
  can_chi_low: boolean
  can_chi_mid: boolean
  can_chi_high: boolean
  can_pon: boolean
  can_daiminkan: boolean
  can_kakan: boolean
  can_ankan: boolean
  can_riichi: boolean
  can_tsumo_agari: boolean
  can_ron_agari: boolean
  can_ryukyoku: boolean
  target_actor: number
}

/** Per-seat state machine, driven by MJAI events. */
export class PlayerState {
  private inner: WasmPlayerStateHandle

  constructor(playerId: 0 | 1 | 2 | 3) {
    this.inner = new wasm.PlayerStateHandle(playerId)
  }

  /** Apply an MJAI event (object form). Returns the resulting candidate. */
  applyEvent(event: object): ActionCandidate {
    const json = this.inner.apply_event(JSON.stringify(event))
    return JSON.parse(json) as ActionCandidate
  }

  /** Encode the current state as (version-specific channels × 34) flat
   *  Float32Array, row-major. */
  encodeObs(version: 3 | 4, atKanSelect = false): Float32Array {
    return this.inner.encode_obs(version, atKanSelect)
  }

  /** Action mask of length ACTION_SPACE (=46). 1 = legal, 0 = illegal. */
  encodeObsMask(version: 3 | 4, atKanSelect = false): Uint8Array {
    return this.inner.encode_obs_mask(version, atKanSelect)
  }

  /** Single-line state dump for debugging. */
  briefInfo(): string {
    return this.inner.brief_info()
  }

  /** Release the wasm handle. After this, no methods may be called. */
  dispose(): void {
    this.inner.free()
  }
}
